name: Remote Responder

on: [repository_dispatch]

jobs:
  ping-pong:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Read dispatch event information
        run: |
          echo "Event '${{ github.event.action }}' received from '${{ github.event.client_payload.repository }}'"
      - name: Send dispatch response
        if: github.event.action == 'ping'
        run: |
          curl -X POST https://api.github.com/repos/emanuelk02/Chess/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.ACCESS_TOKEN }} \
          --data '{"event_type": "pong", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Clone Repository
        if: github.event.action == 'ping'
        run: git clone https://github.com/emanuelk02/Chess.git
      - name: Assemble project .jar
        if: github.event.action == 'ping'      
        run: |
          ls
          cd Chess
          sbt assembly
      - name: Replace lib jar
        if: github.event.action == 'ping'
        run: |
          ls
          rm -rf lib
          mkdir -p lib 
          cp Chess/target/scala-*/Chess-assembly*.jar lib/  
          rm -rf Chess
      - name: Commit changes
        if: github.event.action == 'ping'
        run: |
          ls
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add --all 
          git commit -m "GitHub Actions sbt assemble jar build" -a
      - name: Push changes
        if: github.event.action == 'ping'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
